namespace HSC_Studio
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        void OnLoaded(Object sender, RoutedEventArgs args);
        void OnLoadModel(Object sender, RoutedEventArgs args);
        void OnChangeParam(Object sender, RoutedEventArgs args);
        void OnResetParam(Object sender, RoutedEventArgs args);
        void OnCompositionRendering(Object sender, Object args);
        void OnUnloaded(Object sender, RoutedEventArgs args);
    }
}
