//! NPU 运行时接口生成
//!
//! 生成调用 NPU 模型的运行时代码（Python/C++）。

use crate::npu::graph::NpuGraph;
use crate::npu::backends::RuntimeConfig;

/// 运行时代码生成器
pub struct RuntimeGenerator {
    /// 目标语言
    target: RuntimeTarget,
}

/// 运行时目标语言
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuntimeTarget {
    /// Python (推荐)
    Python,
    /// C++
    Cpp,
    /// 两者都生成
    Both,
}

impl Default for RuntimeTarget {
    fn default() -> Self {
        RuntimeTarget::Python
    }
}

/// 生成的运行时代码
pub struct RuntimeCode {
    /// Python 代码
    pub python: Option<String>,
    /// C++ 头文件
    pub header: Option<String>,
    /// C++ 源文件
    pub source: Option<String>,
}

impl RuntimeGenerator {
    /// 创建运行时生成器
    pub fn new(target: RuntimeTarget) -> Self {
        Self { target }
    }

    /// 生成运行时代码
    pub fn generate(&self, graph: &NpuGraph, config: &RuntimeConfig) -> RuntimeCode {
        match self.target {
            RuntimeTarget::Python => RuntimeCode {
                python: Some(self.generate_python(graph, config)),
                header: None,
                source: None,
            },
            RuntimeTarget::Cpp => RuntimeCode {
                python: None,
                header: Some(self.generate_header(graph, config)),
                source: Some(self.generate_source(graph, config)),
            },
            RuntimeTarget::Both => RuntimeCode {
                python: Some(self.generate_python(graph, config)),
                header: Some(self.generate_header(graph, config)),
                source: Some(self.generate_source(graph, config)),
            },
        }
    }

    /// 生成 Python 运行时代码
    fn generate_python(&self, graph: &NpuGraph, config: &RuntimeConfig) -> String {
        let perf_hint = match config.execution.performance_hint {
            crate::npu::backends::PerformanceHint::Latency => "LATENCY",
            crate::npu::backends::PerformanceHint::Throughput => "THROUGHPUT",
            crate::npu::backends::PerformanceHint::PowerEfficient => "CUMULATIVE_THROUGHPUT",
        };
        let num_streams = config.execution.num_requests;
        let name = &graph.name;

        format!(r#"#!/usr/bin/env python3
"""Auto-generated NPU Runtime for {name}

Generated by HSCC NPU Backend
"""

import numpy as np
from typing import Dict, List, Optional, Tuple

try:
    from openvino.runtime import Core, Tensor, Type
    OPENVINO_AVAILABLE = True
except ImportError:
    OPENVINO_AVAILABLE = False


class {name}Executor:
    """NPU Executor for {name}"""

    def __init__(self, model_path: str, device: str = "NPU"):
        if not OPENVINO_AVAILABLE:
            raise RuntimeError("OpenVINO is required for NPU execution")

        self.core = Core()
        self.model = self.core.read_model(model_path)

        # Check device availability
        available_devices = self.core.available_devices
        if device not in available_devices:
            print("Warning: " + device + " not available. Using AUTO instead.")
            device = "AUTO"

        # Compile model
        self.compiled_model = self.core.compile_model(
            self.model,
            device,
            config={{
                "PERFORMANCE_HINT": "{perf_hint}",
                "NUM_STREAMS": {num_streams},
            }}
        )

        self.infer_request = self.compiled_model.create_infer_request()
        self._device = device

    @property
    def device(self) -> str:
        """Get execution device"""
        return self._device

    def get_input_info(self) -> Dict[str, Tuple[List[int], str]]:
        """Get input tensor info"""
        return {{
            name: (list(port.get_shape()), str(port.get_element_type()))
            for name, port in self._iter_inputs()
        }}

    def get_output_info(self) -> Dict[str, Tuple[List[int], str]]:
        """Get output tensor info"""
        return {{
            name: (list(port.get_shape()), str(port.get_element_type()))
            for name, port in self._iter_outputs()
        }}

    def _iter_inputs(self):
        for port in self.compiled_model.inputs:
            yield port.get_any_name(), port

    def _iter_outputs(self):
        for port in self.compiled_model.outputs:
            yield port.get_any_name(), port

    def infer(self, inputs: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
        """Execute inference

        Args:
            inputs: Dictionary mapping input names to numpy arrays

        Returns:
            Dictionary mapping output names to numpy arrays
        """
        # Prepare input tensors
        input_tensors = {{}}
        for name, array in inputs.items():
            input_tensors[name] = Tensor(array)

        # Set inputs
        self.infer_request.set_input_tensors(input_tensors)

        # Execute
        self.infer_request.infer()

        # Get outputs
        outputs = {{}}
        for name, port in self._iter_outputs():
            outputs[name] = self.infer_request.get_output_tensor(
                port.get_index()
            ).data.copy()

        return outputs

    def __call__(self, **inputs) -> Dict[str, np.ndarray]:
        """Convenient call interface"""
        return self.infer(inputs)


def main():
    import argparse

    parser = argparse.ArgumentParser(description="NPU Inference Runtime")
    parser.add_argument("--model", required=True, help="Path to ONNX/OpenVINO model")
    parser.add_argument("--device", default="NPU", help="Target device")
    args = parser.parse_args()

    executor = {name}Executor(args.model, args.device)

    print("Model: " + args.model)
    print("Device: " + executor.device)
    print("Inputs: " + str(executor.get_input_info()))
    print("Outputs: " + str(executor.get_output_info()))


if __name__ == "__main__":
    main()
"#, name = name, perf_hint = perf_hint, num_streams = num_streams)
    }

    /// 生成 C++ 头文件
    fn generate_header(&self, graph: &NpuGraph, _config: &RuntimeConfig) -> String {
        let name = &graph.name;
        
        let mut input_fields = String::new();
        for input in &graph.inputs {
            input_fields.push_str(&format!(
                "    void* {};  // {}\n",
                input.name,
                input.dtype.to_c_type()
            ));
        }

        let mut output_fields = String::new();
        for output in &graph.outputs {
            output_fields.push_str(&format!(
                "    void* {};  // {}\n",
                output.name,
                output.dtype.to_c_type()
            ));
        }

        format!(r#"// Auto-generated by HSCC NPU Backend
// Model: {name}

#pragma once

#include <vector>
#include <string>
#include <memory>

namespace hsc::npu::{name} {{

// Input/Output structures
struct Inputs {{
{input_fields}}};

struct Outputs {{
{output_fields}}};

class Executor {{
public:
    Executor(const std::string& model_path);
    ~Executor();

    bool initialize();
    bool execute(const Inputs& inputs, Outputs& outputs);
    void finalize();

    const std::string& device() const {{ return device_; }}

private:
    class Impl;
    std::unique_ptr<Impl> impl_;
    std::string device_;
}};

}}  // namespace hsc::npu::{name}
"#, name = name, input_fields = input_fields, output_fields = output_fields)
    }

    /// 生成 C++ 源文件
    fn generate_source(&self, graph: &NpuGraph, _config: &RuntimeConfig) -> String {
        let name = &graph.name;

        format!(r#"// Auto-generated by HSCC NPU Backend
// Model: {name}

#include "{name}_runtime.h"
#include <openvino/openvino.hpp>

namespace hsc::npu::{name} {{

class Executor::Impl {{
public:
    ov::Core core;
    std::shared_ptr<ov::Model> model;
    ov::CompiledModel compiled_model;
    ov::InferRequest infer_request;

    Impl() = default;
}};

Executor::Executor(const std::string& model_path)
    : impl_(std::make_unique<Impl>()) {{
    impl_->model = impl_->core.read_model(model_path);
}}

Executor::~Executor() = default;

bool Executor::initialize() {{
    // Check NPU availability
    auto devices = impl_->core.get_available_devices();
    std::string target_device = "NPU";

    if (std::find(devices.begin(), devices.end(), "NPU") == devices.end()) {{
        target_device = "AUTO";
    }}

    // Compile model
    impl_->compiled_model = impl_->core.compile_model(
        impl_->model,
        target_device
    );

    impl_->infer_request = impl_->compiled_model.create_infer_request();
    device_ = target_device;

    return true;
}}

bool Executor::execute(const Inputs& inputs, Outputs& outputs) {{
    // Set inputs
    // TODO: Implement input/output tensor handling

    // Execute
    impl_->infer_request.infer();

    // Get outputs
    // TODO: Implement output extraction

    return true;
}}

void Executor::finalize() {{
    // Cleanup
}}

}}  // namespace hsc::npu::{name}
"#, name = name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::npu::graph::NpuGraph;

    #[test]
    fn test_python_generation() {
        let generator = RuntimeGenerator::new(RuntimeTarget::Python);
        let graph = NpuGraph::new("test_model");
        let config = RuntimeConfig::default();

        let code = generator.generate(&graph, &config);
        assert!(code.python.is_some());
        assert!(code.python.unwrap().contains("test_model"));
    }
}