//! CPU 后端代码生成器
//!
//! 将 AST 转换为 C++ 代码，支持 OpenMP 并行化

use crate::ast::*;
use crate::cpu::types::{CpuType, TypeMapper};
use std::collections::HashMap;

/// CPU 代码生成器
pub struct CpuCodeGenerator {
    /// 输出代码
    output: String,
    /// 缩进级别
    indent: usize,
    /// 变量映射：变量名 -> C++ 类型
    var_map: HashMap<String, String>,
    /// 是否启用 OpenMP
    enable_openmp: bool,
    /// 是否启用 SIMD
    enable_simd: bool,
    /// 线程数（0 表示自动）
    num_threads: usize,
}

impl CpuCodeGenerator {
    /// 创建新的代码生成器
    pub fn new() -> Self {
        CpuCodeGenerator {
            output: String::new(),
            indent: 0,
            var_map: HashMap::new(),
            enable_openmp: true,
            enable_simd: true,
            num_threads: 0,
        }
    }

    /// 创建带配置的代码生成器
    pub fn with_config(openmp: bool, simd: bool, threads: usize) -> Self {
        CpuCodeGenerator {
            output: String::new(),
            indent: 0,
            var_map: HashMap::new(),
            enable_openmp: openmp,
            enable_simd: simd,
            num_threads: threads,
        }
    }

    /// 启用/禁用 OpenMP
    pub fn set_openmp(&mut self, enable: bool) {
        self.enable_openmp = enable;
    }

    /// 启用/禁用 SIMD
    pub fn set_simd(&mut self, enable: bool) {
        self.enable_simd = enable;
    }

    /// 设置线程数
    pub fn set_num_threads(&mut self, threads: usize) {
        self.num_threads = threads;
    }

    /// 输出字符串
    fn emit(&mut self, s: &str) {
        self.output.push_str(s);
    }

    /// 输出带缩进的行
    fn emitln(&mut self, s: &str) {
        self.output.push_str(&"    ".repeat(self.indent));
        self.output.push_str(s);
        self.output.push('\n');
    }

    /// 输出空行
    fn emit_empty(&mut self) {
        self.output.push('\n');
    }

    /// 增加缩进
    fn indent_inc(&mut self) {
        self.indent += 1;
    }

    /// 减少缩进
    fn indent_dec(&mut self) {
        debug_assert!(self.indent > 0, "indent underflow");
        self.indent = self.indent.saturating_sub(1);
    }

    /// 生成完整程序
    pub fn generate(&mut self, program: &Program) -> String {
        // 生成头文件
        self.generate_includes();

        // 生成设备常量
        self.generate_device_constants();

        // 生成 Buffer 模板类
        self.generate_buffer_template();

        // 生成任务函数
        for task in &program.tasks {
            self.generate_task(task);
        }

        // 生成主机函数
        for func in &program.functions {
            self.generate_function(func);
        }

        // 生成 main 函数
        self.generate_main(program);

        self.output.clone()
    }

    /// 生成头文件包含
    fn generate_includes(&mut self) {
        self.emitln("// Generated by HSCC CPU Backend");
        self.emitln("// DO NOT EDIT - Auto-generated code");
        self.emit_empty();

        // 标准库
        self.emitln("#include <stdio.h>");
        self.emitln("#include <stdlib.h>");
        self.emitln("#include <string.h>");
        self.emitln("#include <stdint.h>");
        self.emitln("#include <vector>");
        self.emitln("#include <string>");
        self.emitln("#include <functional>");
        self.emitln("#include <thread>");
        self.emitln("#include <mutex>");
        self.emitln("#include <atomic>");
        self.emitln("#include <chrono>");
        self.emitln("#include <iostream>");
        self.emitln("#include <cassert>");

        // OpenMP（如果启用）
        if self.enable_openmp {
            self.emitln("#include <omp.h>");
        }

        // SIMD 支持（如果启用）
        if self.enable_simd {
            self.emitln("#include <immintrin.h>  // AVX/SSE intrinsics");
        }

        self.emit_empty();
    }

    /// 生成设备常量
    fn generate_device_constants(&mut self) {
        self.emitln("// Device constants");
        self.emitln("enum Device {");
        self.indent_inc();
        self.emitln("CPU = -1,");
        self.emitln("GPU = 0,");
        self.emitln("NPU = 1,");
        self.emitln("FPGA = 2,");
        self.emitln("Host = -1");
        self.indent_dec();
        self.emitln("};");
        self.emit_empty();
    }

    /// 生成 Buffer 模板类
    fn generate_buffer_template(&mut self) {
        self.emitln("// Buffer template for multi-dimensional arrays");
        self.emitln("template<typename T>");
        self.emitln("class Buffer {");
        self.indent_inc();

        // 成员变量
        self.emitln("private:");
        self.emitln("    T* data_;");
        self.emitln("    size_t size_;");
        self.emitln("    std::vector<size_t> dims_;");
        self.emitln("    int device_;");
        self.emitln("    bool owns_data_;");
        self.emit_empty();

        // 构造函数和析构函数
        self.emitln("public:");
        self.emitln("    Buffer() : data_(nullptr), size_(0), device_(-1), owns_data_(false) {}");
        self.emit_empty();

        // 带形状的构造函数
        self.emitln("    Buffer(std::initializer_list<size_t> shape) : device_(-1), owns_data_(true) {");
        self.indent_inc();
        self.emitln("dims_ = shape;");
        self.emitln("size_ = 1;");
        self.emitln("for (auto d : dims_) size_ *= d;");
        self.emitln("data_ = new T[size_]();");
        self.indent_dec();
        self.emitln("    }");
        self.emit_empty();

        // 析构函数
        self.emitln("    ~Buffer() {");
        self.indent_inc();
        self.emitln("if (owns_data_ && data_) { delete[] data_; }");
        self.indent_dec();
        self.emitln("    }");
        self.emit_empty();

        // 禁止拷贝
        self.emitln("    Buffer(const Buffer&) = delete;");
        self.emitln("    Buffer& operator=(const Buffer&) = delete;");
        self.emit_empty();

        // 允许移动
        self.emitln("    Buffer(Buffer&& other) noexcept");
        self.indent_inc();
        self.emitln(": data_(other.data_), size_(other.size_), dims_(std::move(other.dims_)),");
        self.emitln("  device_(other.device_), owns_data_(other.owns_data_) {");
        self.emitln("other.data_ = nullptr;");
        self.emitln("other.owns_data_ = false;");
        self.indent_dec();
        self.emitln("    }");
        self.emit_empty();

        // 静态工厂方法
        self.emitln("    static Buffer zeros(std::initializer_list<size_t> shape) {");
        self.indent_inc();
        self.emitln("Buffer buf(shape);");
        self.emitln("return buf;");
        self.indent_dec();
        self.emitln("    }");
        self.emit_empty();

        self.emitln("    static Buffer ones(std::initializer_list<size_t> shape) {");
        self.indent_inc();
        self.emitln("Buffer buf(shape);");
        self.emitln("for (size_t i = 0; i < buf.size_; ++i) buf.data_[i] = T(1);");
        self.emitln("return buf;");
        self.indent_dec();
        self.emitln("    }");
        self.emit_empty();

        // 访问器
        self.emitln("    // Accessors");
        self.emitln("    T* data() { return data_; }");
        self.emitln("    const T* data() const { return data_; }");
        self.emitln("    size_t size() const { return size_; }");
        self.emitln("    size_t ndim() const { return dims_.size(); }");
        self.emitln("    const size_t* shape() const { return dims_.data(); }");
        self.emitln("    int device() const { return device_; }");
        self.emit_empty();

        // 一维访问
        self.emitln("    // Element access (1D)");
        self.emitln("    T& operator[](size_t i) { return data_[i]; }");
        self.emitln("    const T& operator[](size_t i) const { return data_[i]; }");
        self.emit_empty();

        // 设备操作
        self.emitln("    // Device operations");
        self.emitln("    Buffer& place_on(int device) {");
        self.indent_inc();
        self.emitln("this->device_ = device;");
        self.emitln("return *this;");
        self.indent_dec();
        self.emitln("    }");
        self.emit_empty();

        self.emitln("    Buffer& move_to(int device) {");
        self.indent_inc();
        self.emitln("// CPU backend: no actual data movement needed");
        self.emitln("this->device_ = device;");
        self.emitln("return *this;");
        self.indent_dec();
        self.emitln("    }");
        self.emit_empty();

        self.indent_dec();
        self.emitln("};");
        self.emit_empty();
    }

    /// 生成任务函数
    fn generate_task(&mut self, task: &Task) {
        let task_name = &task.name;

        // 参数
        let params: Vec<String> = task.params.iter().map(|param| {
            let cpu_type = CpuType::from_ast(&param.ty);
            if cpu_type.is_buffer() {
                format!("Buffer<{}>& {}", cpu_type.element_type.as_ref().unwrap().name, param.name)
            } else {
                format!("{} {}", cpu_type.name, param.name)
            }
        }).collect();

        let params_str = if params.is_empty() { "".to_string() } else { params.join(", ") };

        // 函数签名
        self.emitln(&format!("void {}({}) {{", task_name, params_str));
        self.indent_inc();

        // 生成任务体
        self.generate_block(&task.body);

        self.indent_dec();
        self.emitln("}");
        self.emit_empty();
    }

    /// 生成主机函数
    fn generate_function(&mut self, func: &Function) {
        // 返回类型
        let return_type = match &func.return_type {
            Some(ty) => {
                let cpu_type = CpuType::from_ast(ty);
                cpu_type.name
            }
            None => "void".to_string(),
        };

        // 参数
        let params: Vec<String> = func.params.iter().map(|param| {
            let cpu_type = CpuType::from_ast(&param.ty);
            if cpu_type.is_buffer() {
                format!("Buffer<{}>& {}", cpu_type.element_type.as_ref().unwrap().name, param.name)
            } else {
                format!("{} {}", cpu_type.name, param.name)
            }
        }).collect();

        let params_str = if params.is_empty() { "".to_string() } else { params.join(", ") };

        // 函数签名
        self.emitln(&format!("{} {}({}) {{", return_type, func.name, params_str));
        self.indent_inc();

        // 函数体
        self.generate_block(&func.body);

        self.indent_dec();
        self.emitln("}");
        self.emit_empty();
    }

    /// 生成块
    fn generate_block(&mut self, block: &Block) {
        for stmt in &block.statements {
            self.generate_statement(stmt);
        }
    }

    /// 生成语句
    fn generate_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Let { mutable: _, name, ty, init } => {
                let cpu_type = ty.as_ref()
                    .map(|t| CpuType::from_ast(t).name)
                    .unwrap_or_else(|| "auto".to_string());
                
                if let Some(expr) = init {
                    let init_expr = self.generate_expression(expr);
                    self.emitln(&format!("{} {} = {};", cpu_type, name, init_expr));
                } else {
                    self.emitln(&format!("{} {};", cpu_type, name));
                }
            }

            Statement::Return(value) => {
                if let Some(expr) = value {
                    let expr_str = self.generate_expression(expr);
                    self.emitln(&format!("return {};", expr_str));
                } else {
                    self.emitln("return;");
                }
            }

            Statement::Expr(expr) => {
                let expr_str = self.generate_expression(expr);
                self.emitln(&format!("{};", expr_str));
            }

            Statement::If { condition, then_branch, else_branch } => {
                let cond = self.generate_expression(condition);
                self.emitln(&format!("if ({}) {{", cond));
                self.indent_inc();
                self.generate_block(then_branch);
                self.indent_dec();

                if let Some(else_block) = else_branch {
                    self.emitln("} else {");
                    self.indent_inc();
                    self.generate_block(else_block);
                    self.indent_dec();
                }
                self.emitln("}");
            }

            Statement::While { condition, body } => {
                let cond = self.generate_expression(condition);
                self.emitln(&format!("while ({}) {{", cond));
                self.indent_inc();
                self.generate_block(body);
                self.indent_dec();
                self.emitln("}");
            }

            Statement::For { var, range, body } => {
                let start_expr = self.generate_expression(&range.0);
                let end_expr = self.generate_expression(&range.1);

                self.emitln(&format!("for (int {} = {}; {} < {}; ++{}) {{",
                    var, start_expr, var, end_expr, var));
                self.indent_inc();
                self.generate_block(body);
                self.indent_dec();
                self.emitln("}");
            }

            Statement::ParallelFor { var, range, body } => {
                let start_expr = self.generate_expression(&range.0);
                let end_expr = self.generate_expression(&range.1);

                if self.enable_openmp {
                    self.emitln("#pragma omp parallel for schedule(static)");
                }

                self.emitln(&format!("for (int {} = {}; {} < {}; ++{}) {{",
                    var, start_expr, var, end_expr, var));
                self.indent_inc();
                self.generate_block(body);
                self.indent_dec();
                self.emitln("}");
            }

            Statement::Loop(body) => {
                self.emitln("while (true) {");
                self.indent_inc();
                self.generate_block(body);
                self.indent_dec();
                self.emitln("}");
            }

            Statement::Break => {
                self.emitln("break;");
            }

            Statement::Continue => {
                self.emitln("continue;");
            }
        }
    }

    /// 生成表达式
    fn generate_expression(&mut self, expr: &Expression) -> String {
        match expr {
            Expression::Integer(n) => n.to_string(),
            Expression::Float(f) => format!("{}f", f),
            Expression::Bool(b) => b.to_string(),
            Expression::String(s) => format!("\"{}\"", s),
            Expression::Nil => "nullptr".to_string(),
            Expression::Identifier(name) => name.clone(),
            Expression::Path(path) => {
                path.segments.iter()
                    .map(|s| s.ident.as_str())
                    .collect::<Vec<_>>()
                    .join("::")
            }
            Expression::Binary { left, op, right } => {
                let left_expr = self.generate_expression(left);
                let right_expr = self.generate_expression(right);
                let op_str = self.binary_op_to_cpp(op);
                format!("({} {} {})", left_expr, op_str, right_expr)
            }
            Expression::Call { func, args } => {
                let func_str = self.generate_expression(func);
                let args_str: Vec<String> = args.iter()
                    .map(|a| self.generate_expression(a))
                    .collect();
                format!("{}({})", func_str, args_str.join(", "))
            }
            Expression::FieldAccess { obj, field } => {
                let obj_expr = self.generate_expression(obj);
                format!("{}.{}", obj_expr, field)
            }
            Expression::Index { obj, index } => {
                let obj_expr = self.generate_expression(obj);
                let index_expr = self.generate_expression(index);
                format!("{}[{}]", obj_expr, index_expr)
            }
            Expression::MethodCall { obj, method, args } => {
                let obj_expr = self.generate_expression(obj);
                let args_str: Vec<String> = args.iter()
                    .map(|a| self.generate_expression(a))
                    .collect();
                format!("{}.{}({})", obj_expr, method, args_str.join(", "))
            }
            Expression::PlaceOn { expr, device } => {
                let expr_str = self.generate_expression(expr);
                let device_str = self.generate_expression(device);
                format!("{}.place_on({})", expr_str, device_str)
            }
            Expression::MoveTo { expr, device } => {
                let expr_str = self.generate_expression(expr);
                let device_str = self.generate_expression(device);
                format!("{}.move_to({})", expr_str, device_str)
            }
            Expression::Await(inner) => {
                // Await 在 CPU 后端是同步调用
                self.generate_expression(inner)
            }
            Expression::Array(elements) => {
                let elements_str: Vec<String> = elements.iter()
                    .map(|e| self.generate_expression(e))
                    .collect();
                format!("{{{}}}", elements_str.join(", "))
            }
            Expression::Spawn { device, task, await_ } => {
                let task_str = self.generate_expression(task);
                if let Some(dev) = device {
                    let dev_str = self.generate_expression(dev);
                    format!("/* spawn on {} */ {}", dev_str, task_str)
                } else {
                    format!("/* spawn */ {}", task_str)
                }
            }
        }
    }

    /// 将二元操作符转换为 C++ 表示
    fn binary_op_to_cpp(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
            BinaryOp::Eq => "==",
            BinaryOp::Ne => "!=",
            BinaryOp::Lt => "<",
            BinaryOp::Le => "<=",
            BinaryOp::Gt => ">",
            BinaryOp::Ge => ">=",
        }
    }

    /// 生成 main 函数
    fn generate_main(&mut self, program: &Program) {
        self.emitln("int main(int argc, char** argv) {");
        self.indent_inc();

        // 初始化 OpenMP
        if self.enable_openmp {
            self.emitln("// Initialize OpenMP");
            if self.num_threads > 0 {
                self.emitln(&format!("omp_set_num_threads({});", self.num_threads));
            }
            self.emitln("printf(\"Running with %d threads\\n\", omp_get_max_threads());");
            self.emit_empty();
        }

        // 调用主函数或生成测试代码
        self.emitln("// Main program");
        self.emitln("printf(\"CPU backend execution\\n\");");

        // 如果有名为 main 的函数，调用它
        let has_main = program.functions.iter().any(|f| f.name == "main");
        if has_main {
            self.emitln("main();");
        }

        self.emit_empty();
        self.emitln("return 0;");

        self.indent_dec();
        self.emitln("}");
    }
}

impl Default for CpuCodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

/// 生成 CPU C++ 代码
pub fn generate_cpu_code(program: &Program) -> String {
    let mut generator = CpuCodeGenerator::new();
    generator.generate(program)
}

/// 生成带配置的 CPU C++ 代码
pub fn generate_cpu_code_with_config(program: &Program, openmp: bool, simd: bool, threads: usize) -> String {
    let mut generator = CpuCodeGenerator::with_config(openmp, simd, threads);
    generator.generate(program)
}
