namespace Live2DWinRT
{
    [bindable]
    [default_interface]
    runtimeclass Live2DModel
    {
        Live2DModel();
        void Initialize(Windows.UI.Xaml.Controls.SwapChainPanel panel);
        void LoadModel(String moc3Path, String model3JsonPath, String textureDir);
        void Update(Single deltaTime);
        void Render();
        void SetParameter(String id, Single value);

        // 可选事件
        event Windows.Foundation.TypedEventHandler<Live2DModel, Object> ModelLoaded;
    }
}